seed_index: 0
deterministic: False

trainer:
  log_every_n_steps: 1
  fast_dev_run: False
  accelerator: 'gpu'
  devices: 1
  precision: 32
  max_steps: -1
  num_sanity_val_steps: 3
  gradient_clip_val: 10.0
  val_check_interval: 1.0
  deterministic: ${train.deterministic}

restore:
  ckpt_or_run_path: null
  mode: finetune # null, finetune, hotstart, continue

monitor:
  metric: 'acc/val'
  mode: 'max'

callbacks:
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
    log_momentum: False

  - _target_: pytorch_lightning.callbacks.progress.tqdm_progress.TQDMProgressBar
    refresh_rate: 20
  # - _target_: pytorch_lightning.callbacks.EarlyStopping
  #   patience: 42
  #   verbose: False
  #   monitor: ${train.monitor.metric}
  #   mode: ${train.monitor.mode}

  # - _target_: pytorch_lightning.callbacks.ModelCheckpoint
  #   dirpath: ${misc.checkpoint_dir} 
  #   filename: "${nn.encoder.model_name}_${num_tasks}tasks"
  #   save_top_k: 1 
  #   save_last: False  
  #   verbose: False
  #   monitor: ${train.monitor.metric}
  #   mode: ${train.monitor.mode}
  #   save_on_train_epoch_end: False 

logging:
  upload:
    run_files: true
    source: true

  logger:
    _target_: lightning.pytorch.loggers.WandbLogger

    project: ${core.project_name}
    entity: gladia
    log_model: false
    mode: 'online'
    tags: ${core.tags}

  wandb_watch:
    log: null
    log_freq: 100
    log_graph: false
