_target_: model_merging.data.dataset.load_dataset
name: PCAM
ft_epochs: 1
preprocess_fn: ??
hf_dataset: 
  _target_: datasets.load_dataset
  path: 1aurent/PatchCamelyon
classnames_override:
  - "lymph node"
  - "lymph node containing metastatic tumor tissue"
