_target_: model_merging.data.dataset.load_dataset
name: STL10
ft_epochs: 6
preprocess_fn: ???
hf_dataset: 
  _target_: datasets.load_dataset
  path: tanganke/stl10

label_map:
  0: 0  # airplane
  2: 1  # car
  1: 2  # bird
  3: 3  # cat
  4: 4  # deer
  5: 5  # dog
  6: 7  # horse
  7: 8  # monkey
  8: 9  # ship
  9: 10  # truck

classnames_override: 
  - "airplane"
  - "automobile"
  - "bird"
  - "cat"
  - "deer"
  - "dog"
  - "frog"
  - "horse"
  - "monkey"
  - "ship"
  - "truck"