_target_: model_merging.model.encoder.ImageEncoder
model_name: ViT-B-32 # ViT-B-32, ViT-L-14
openclip_cachedir: ${misc.openclip_cachedir}
cache_dir: null
keep_lang: false  
layer_to_hook: mlp # attn, mlp 
layer_num_to_hook: 9 # <=11