
_target_: model_merging.merger.tsv.TaskSingularVectorsMerger
svd_path: "${oc.env:MODELS_PATH}svd_dict_${nn.encoder.model_name}.pt"
svd_compress_factor: null 
non_matrix_params_aggregation: "mean" # "base_model"
